export const messageList = [
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Hey",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:01Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Hey, what's up?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:05Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "You free now?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:10Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Yeah, for a bit",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:15Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Checked the new build?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:20Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Pulling it now",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:25Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "UI got some tweaks",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:30Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Hope nothing broke",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:35Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Tests passed",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:40Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Mostly?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:45Z",
  },

  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Okay yeah, mostly 😅",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:50Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Classic",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:00:55Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Any errors yet?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:00Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "None so far",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:05Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Good sign",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:10Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "API responses look fine",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:15Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Latency?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:20Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Stable",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:25Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Nice",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:30Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Checking UI now",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:35Z",
  },

  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Anything off?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:40Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Button padding slightly weird",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:45Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "How weird?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:50Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Designer will notice",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:01:55Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Users won’t",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:00Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "True",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:05Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "QA will cry though",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:10Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "They always do",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:15Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Deploy today?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:20Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Yes",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:25Z",
  },

  // 61–100
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Deploying now?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:30Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Starting pipeline",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:35Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Fingers crossed",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:40Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Build passed",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:45Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Nice",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:50Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Production live",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:02:55Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Monitoring logs",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:00Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "No errors yet",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:05Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "CPU stable",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:10Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Memory stable",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:15Z",
  },

  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "We survived",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:20Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Barely",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:25Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Lunch?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:30Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "Definitely",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:35Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "You earned it",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:40Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "So did you",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:45Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Shall we log off?",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:50Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "After lunch 😄",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:03:55Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_1",
    contentType: "text",
    textMessage: "Deal",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:04:00Z",
  },
  {
    conversationId: "conv_001",
    senderId: "user_2",
    contentType: "text",
    textMessage: "See you",
    mediaUrl: "",
    fileName: "",
    fileSize: "",
    isEdited: false,
    isDeleted: false,
    sendedAt: "2025-01-01T09:04:05Z",
  },
];
